# Generated by Django 4.0.6 on 2022-07-14 17:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.SlugField(default=False, null=True)),
                ('category_img', models.ImageField(upload_to='category_image')),
                ('category_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='Slideshow')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_image1', models.ImageField(upload_to='product_image')),
                ('product_Name', models.CharField(blank=True, max_length=200)),
                ('prices', models.FloatField(default=0.0)),
                ('product_description', models.TextField(max_length=100)),
                ('Condition', models.CharField(choices=[('N', 'New'), ('ULN', 'Used-like New'), ('NG', 'New-Good'), ('UF', 'Used-Fair')], default='N', max_length=5)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('facebook_userName', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_number', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
